### ISSUE TITLE
Update resolver

### ISSUE THREAD

**Issue by XakepSDK** [ljnelson/microbean-maven-cdi#1]
Can you update maven resolver to 1.3.3?
Does not work with 1.3.3
`java.lang.ClassNotFoundException: org.eclipse.aether.internal.impl.DefaultDependencyCollector
`
I found class with same name in
`org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector`

**Comment by ljnelson** [comment]
Hello; thanks for using microBean Maven CDI.  I agree with you that this project needs a refresher in general.

**Comment by ljnelson** [comment]
Hi, @XakepSDK; I've pushed [version 0.4.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/microbean/microbean-maven-cdi/0.4.0-SNAPSHOT/) to the [Sonatype snapshot repository](https://oss.sonatype.org/content/repositories/snapshots/); let me know how it goes.

**Comment by XakepSDK** [comment]
Should i preconfigure it somehow?
https://gist.github.com/XakepSDK/8406989957f07083316f3201e4b06288
https://gist.github.com/XakepSDK/8fd80d6d6fcf6a993dd00df4adb7323a

**Comment by ljnelson** [comment]
These exceptions look to me like perhaps this project is not even on your classpath.  Please provide a simple, self-contained reproducible example of your problem.  Thanks!

**Comment by ljnelson** [comment]
Version 0.4.0 released with new versions; closing.
